### ISSUE TITLE
running on Windows

### ISSUE THREAD

**Issue by eried** [zer0-pole/emotiv-lsl#2]
Hi! thanks for this. I am trying to run this on Windows, and first the hid error think it is fixed with [this](https://stackoverflow.com/questions/70894915/cant-load-hidapi-with-python-library-hid-on-windows) but now there is something about crypto failing, tried with crypto, pycrypto and pycryptodome:
![image](https://github.com/zer0-pole/emotiv-lsl/assets/1091420/54c4e652-3050-42c7-9d19-97a4ba464ebb)

anything else I could try?

**Comment by zer0-pole** [comment]
Hello, did you install deps?
`python -m pipenv install`

This error shows that your device didn't connected.
Did you connect headset via dongle? Is device have light from two indicators?

**Comment by eried** [comment]
yes, installed the deps, I tried only via bluetooth, I will test with the dongle this afternoon. Anyhow thanks again for the project! :)

**Comment by eried** [comment]
OH! with the dongle it works! fantastic!!
