### ISSUE TITLE
Emotiv EPOC X data decode

### ISSUE THREAD

**Issue by Gpandaa** [zer0-pole/emotiv-lsl#3]
Thank you for your wonderful work! It can help me get raw data from EPOC X. But through observing waveform, I found these data may not correct EEG data. This phenomenon may be caused by incorrect decoding (wrong AES key) ?

**Comment by vtr0n** [comment]
Hello! 
Sorry, I missed this message. 
Can you tell us more about the problem?
It might be worth trying to play around with the settings. Set Hertz to 128.
Please note that the data comes in microvolts

**Comment by Lakasabasz** [comment]
I have same question. I adjusted SRATE to 128 and output is strange. Light theme is EmotivPRO, dark theme is bsl_stream_viewer
![Zrzut ekranu 2024-02-11 221411](https://github.com/vtr0n/emotiv-lsl/assets/18248077/01ed14ca-3db9-4a96-a66e-4385170a64d2)

bsl settings:
Scale: 2.5mV, CAR enabled, Bandpass filter 1, 40

EmotivPro settings:
Cannel spacing (uV): 200

**Comment by Howchie** [comment]
@vtr0n looking through the code, is it possible that in convertEPOC_PLUS the "-128" is supposed to use the SRATE? Is it mistakenly hardcoding a sample rate of 128 or am I misunderstanding?

**Comment by vtr0n** [comment]
@Lakasabasz how did you set up this experiment?
The graphs are very similar, as if they were just different scales

**Comment by Lakasabasz** [comment]
@vtr0n sorry for late response, I didn't see gh notifications (weird)
I connected headset via USB dongle and I started at the same time both Emotiv Pro and python scripts. Then I aligned both windows to see graphs from both apps. Nothing more.

**Comment by vtr0n** [comment]
For the purity of the experiment, I would do the following: I downloaded the raw data from the emotiv app and built a chart based on this data. Or even compared the numbers. I've done this before- they were the same. Most likely, the application has its own filters and/or special settings

**Comment by bahanhan** [comment]
> I have same question. I adjusted SRATE to 128 and output is strange. Light theme is EmotivPRO, dark theme is bsl_stream_viewer ![Zrzut ekranu 2024-02-11 221411](https://private-user-images.githubusercontent.com/18248077/303948105-01ed14ca-3db9-4a96-a66e-4385170a64d2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI1OTIyMzcsIm5iZiI6MTczMjU5MTkzNywicGF0aCI6Ii8xODI0ODA3Ny8zMDM5NDgxMDUtMDFlZDE0Y2EtM2RiOS00YTk2LWE2NmUtNDM4NTE3MGE2NGQyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI2VDAzMzIxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIyYTU5MGVmM2RiNjc5MGQ0NmZkMGQ3ZmMzNjZjMzQ2ZGI4NmM0N2JjNGE5MWNlZTA3ZDMzYTIwYjc5Y2U4YWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ksb-EXca-3_P_OhY7Txj2oTBnVTyeh7yfhvvWwNWtyE)
> 
> bsl settings: Scale: 2.5mV, CAR enabled, Bandpass filter 1, 40
> 
> EmotivPro settings: Cannel spacing (uV): 200

Thank you very much for your emotiv lsl project. But I also encountered the same problem. Have you solved it later? Although the trends of the images are quite similar, there is a significant difference in the values

**Comment by vtr0n** [comment]
@bahanhan 
This is not a problem, the library gives a pure raw eeg signal. The emotiv application corrects the signal using 2 sensors as the primary output (you can read here https://emotiv.gitbook.io/epoc-x-user-manual/getting-started/changing-reference-sensor-location ). To ensure that the signal is correct, you need to export the emotiv raw signal from the application and build a plot. I did that - the data was identical.
