### ISSUE TITLE
What models are supported?

### ISSUE THREAD

**Issue by chimura** [zer0-pole/emotiv-lsl#4]
Hello,

Firstly, thank you for this project!

I wanted to know what Emotiv models are supported by this code - only Epoc X?

Sorry if this information is available and I missed it. I'm looking for some way of making a Flex 1.0 model work.

**Comment by vtr0n** [comment]
Hello
Its working only with Epoc X :(
But you can implement realisation for Flex version, you can look for examples here:
https://github.com/vtr0n/emotiv-lsl/blob/main/emotiv_lsl/emotiv_epoc_x.py
And crypto key find here https://github.com/CymatiCorp/CyKit/tree/master
Or ask some advise in discord channel in CyKit repo
