### ISSUE TITLE
Emotiv Pro EEG Data vs. Emotiv-lsl EEG Data

### ISSUE THREAD

**Issue by ghost** [zer0-pole/emotiv-lsl#7]
Is there any difference between the EEG recording from Emotiv Pro Software and Emotiv-lsl real-time EEG data?(Different pre-processing etc.)

**Comment by Lakasabasz** [comment]
Yes, there is. Probably Pro software uses one of sensors as calibration sensor and all recordings are relative. lsl produces raw data. But this is only my theory and I am not able to verify (I don't have pro license and I can't download raw data from Pro).

See #3

**Comment by vtr0n** [comment]
I have already done an experiment, listening to tshark stream and looking at emoiv plot - they were the same.
You can repeat this and write here - very interesting!
The examples include pyshark implementation

**Comment by vtr0n** [comment]
This is not a problem, the library gives a pure raw eeg signal. The emotiv application corrects the signal using 2 sensors as the primary output (you can read here https://emotiv.gitbook.io/epoc-x-user-manual/getting-started/changing-reference-sensor-location ). To ensure that the signal is correct, you need to export the emotiv raw signal from the application and build a plot. I did that - the data was identical.
